### ISSUE TITLE
Error on authentification with Heroku account

### ISSUE THREAD

**Issue by EdwardBock** [coralproject/talk-install#2]
Hey there,

I tried you install app but got an crash when I try to authenticate.

<img width="875" alt="bildschirmfoto 2017-04-27 um 13 13 06" src="https://cloud.githubusercontent.com/assets/3862417/25480920/464c027a-2b4b-11e7-84df-4587b332c265.png">

Klick on "Login with Heroku" and get this.

```
Cannot create property 'type' on boolean 'true'

TypeError: Cannot create property 'type' on boolean 'true'
    at allFailed (/var/sites/coralproject/talk-install-master/node_modules/passport/lib/middleware/authenticate.js:113:20)
    at attempt (/var/sites/coralproject/talk-install-master/node_modules/passport/lib/middleware/authenticate.js:167:28)
    at Strategy.strategy.fail (/var/sites/coralproject/talk-install-master/node_modules/passport/lib/middleware/authenticate.js:284:9)
    at verified (/var/sites/coralproject/talk-install-master/node_modules/passport-oauth2/lib/strategy.js:173:40)
    at Strategy.passport.use.HerokuStrategy [as _verify] (/var/sites/coralproject/talk-install-master/passport.js:32:12)
    at /var/sites/coralproject/talk-install-master/node_modules/passport-oauth2/lib/strategy.js:193:24
    at /var/sites/coralproject/talk-install-master/node_modules/passport-heroku/lib/strategy.js:108:5
    at passBackControl (/var/sites/coralproject/talk-install-master/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/var/sites/coralproject/talk-install-master/node_modules/oauth/lib/oauth2.js:143:7)
    at emitNone (events.js:91:20)
```

I pass the environmental configuration values via package.json script like:

```json
{
...
scripts: {
  "start": "SESSION_SECRET=... HEROKU_OAUTH_ID=... HEROKU_OAUTH_SECRET=... node --use_strict ./bin/www"
}
...
}
```

Can you help me?

**Comment by wyattjoh** [comment]
What version of node are you running this with @EdwardBock?

**Comment by EdwardBock** [comment]
I'm running on the latest v7.9.0

**Comment by wyattjoh** [comment]
The issue you're encountering @EdwardBock is that PassportJS expects that the `failureFlash` parameter (which you can see here: ) is a boolean, yet because you enabled `--use_strict` it won't let it to get treated like an object, so it fails. This is unfortunately an upstream issue and our use of the feature matches how they document it here: http://passportjs.org/docs#flash-messages

As a solution, I've patched the codebase to work as expected for your usecase, I'll see if I can file an upstream issue with Passport.
